### PR TITLE
France ressources publiques

### PR DESCRIPTION
**Pull request by MayWorkman**

### CODE REVIEW

**Comment by jonvellacott** [comment]
I don't have time this week to do a full code review (I am in meetings in Orlando). But I can merge this commit in or possible deploy. Even better, you can merge and deploy yourself. Is there anything you need me to do here?

**Comment by MayWorkman** [comment]
Jon,

Thanks for asking. David is looking at the code and will deploy it. No need
for you to look into it.

May

2016-05-17 13:14 GMT+02:00 Jon Vellacott <notifications@github.com>:

> I don't have time this week to do a full code review (I am in meetings in
> Orlando). But I can merge this commit in or possible deploy. Even better,
> you can merge and deploy yourself. Is there anything you need me to do here?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/GlobalTechnology/OpsInABox/pull/62#issuecomment-219688400>
>



-- 
*May Workman*
may.workman@cru.org

**Comment by davidviolleau** [comment]
Wouhou ! :+1:

**Comment by trentschaller** [comment]
Published and tested

**Pull request merged**
